import type { Metadata } from "next";
import "./globals.css";
import "../../public/fonts/gellix.css";
import ParticleCanvas from "@/app/components/ParticleCanvas";
import GlitchCanvas from "@/app/components/GlitchCanvas";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ParticleCanvas />
        <GlitchCanvas />
        {children}
      </body>
    </html>
  );
}
